apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-container
          image: django_app:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: DEBUG
              value: "true"
            - name: DJANGO_SETTINGS_MODULE
              value: "myapp.settings"

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # type: NodePort
